import React, { useState } from 'react';
import {
  Database,
  Archive,
  Download,
  RotateCcw,
  CheckCircle2,
  AlertTriangle,
  ShieldAlert,
  Clock,
  HardDrive,
  FileCode,
  Lock,
  RefreshCw,
  Check,
  ChevronRight,
  Shield,
  HelpCircle,
} from 'lucide-react';
import { useData } from '../../context/DataContext';
import { useAuth } from '../../context/AuthContext';
import { BackupRecord } from '../../types';
import {
  RETENTION_POLICIES,
  DISASTER_RECOVERY_RUNBOOKS,
  DisasterRecoveryRunbook,
} from '../../services/backupService';

export const BackupDisasterRecoveryTab: React.FC = () => {
  const { currentUser } = useAuth();
  const {
    backupRecords,
    createBackupRecord,
    restoreFromBackup,
    logAuditEvent,
  } = useData();

  const [activeSubTab, setActiveSubTab] = useState<'BACKUPS' | 'RESTORE' | 'RETENTION' | 'RUNBOOKS'>('BACKUPS');
  const [isCreatingBackup, setIsCreatingBackup] = useState(false);
  const [backupSuccessMessage, setBackupSuccessMessage] = useState<string | null>(null);

  // 8-Step Restore Wizard State
  const [selectedBackupForRestore, setSelectedBackupForRestore] = useState<BackupRecord | null>(null);
  const [restoreStep, setRestoreStep] = useState<number>(1);
  const [isDryRunVerified, setIsDryRunVerified] = useState<boolean>(false);
  const [managementConfirmText, setManagementConfirmText] = useState<string>('');
  const [isRestoring, setIsRestoring] = useState<boolean>(false);
  const [restoreCompleteMessage, setRestoreCompleteMessage] = useState<string | null>(null);

  // Selected Runbook
  const [selectedRunbook, setSelectedRunbook] = useState<DisasterRecoveryRunbook | null>(
    DISASTER_RECOVERY_RUNBOOKS[0]
  );

  const handleManualBackup = async () => {
    setIsCreatingBackup(true);
    try {
      const record = await createBackupRecord('MANUAL');
      setBackupSuccessMessage(`Backup ${record.id} successfully created and verified via SHA-256.`);
      setTimeout(() => setBackupSuccessMessage(null), 5000);
      logAuditEvent({
        recordType: 'BACKUP',
        recordId: record.id,
        action: 'MANUAL_BACKUP_CREATED',
        description: `Manual database snapshot generated by ${currentUser.name} ${currentUser.surname}`,
      });
    } finally {
      setIsCreatingBackup(false);
    }
  };

  const handleStartRestoreWizard = (bkp: BackupRecord) => {
    setSelectedBackupForRestore(bkp);
    setRestoreStep(1);
    setIsDryRunVerified(false);
    setManagementConfirmText('');
    setRestoreCompleteMessage(null);
    setActiveSubTab('RESTORE');
  };

  const handleExecuteRestore = async () => {
    if (!selectedBackupForRestore) return;
    setIsRestoring(true);
    try {
      const result = await restoreFromBackup(selectedBackupForRestore.id, { dryRun: false });
      setRestoreCompleteMessage(result.message);
      setRestoreStep(8);
      logAuditEvent({
        recordType: 'RESTORE',
        recordId: selectedBackupForRestore.id,
        action: 'DATABASE_RESTORE_COMPLETED',
        description: `Database successfully restored from ${selectedBackupForRestore.id} with ${result.restoredCount} entities.`,
      });
    } finally {
      setIsRestoring(false);
    }
  };

  return (
    <div className="space-y-4 text-xs">
      {/* Sub Tabs */}
      <div className="flex bg-slate-900 rounded-xl p-1 border border-slate-800 font-semibold overflow-x-auto scrollbar-none">
        <button
          onClick={() => setActiveSubTab('BACKUPS')}
          className={`flex items-center gap-1.5 px-4 py-2 rounded-lg transition whitespace-nowrap ${
            activeSubTab === 'BACKUPS'
              ? 'bg-amber-600 text-slate-950 font-black shadow-sm'
              : 'text-slate-400 hover:text-slate-200'
          }`}
        >
          <HardDrive className="w-4 h-4" />
          <span>Backup Snapshots ({backupRecords.length})</span>
        </button>

        <button
          onClick={() => setActiveSubTab('RESTORE')}
          className={`flex items-center gap-1.5 px-4 py-2 rounded-lg transition whitespace-nowrap ${
            activeSubTab === 'RESTORE'
              ? 'bg-amber-600 text-slate-950 font-black shadow-sm'
              : 'text-slate-400 hover:text-slate-200'
          }`}
        >
          <RotateCcw className="w-4 h-4" />
          <span>8-Step Restore Wizard</span>
        </button>

        <button
          onClick={() => setActiveSubTab('RETENTION')}
          className={`flex items-center gap-1.5 px-4 py-2 rounded-lg transition whitespace-nowrap ${
            activeSubTab === 'RETENTION'
              ? 'bg-amber-600 text-slate-950 font-black shadow-sm'
              : 'text-slate-400 hover:text-slate-200'
          }`}
        >
          <Clock className="w-4 h-4" />
          <span>POPIA Retention Policies</span>
        </button>

        <button
          onClick={() => setActiveSubTab('RUNBOOKS')}
          className={`flex items-center gap-1.5 px-4 py-2 rounded-lg transition whitespace-nowrap ${
            activeSubTab === 'RUNBOOKS'
              ? 'bg-amber-600 text-slate-950 font-black shadow-sm'
              : 'text-slate-400 hover:text-slate-200'
          }`}
        >
          <ShieldAlert className="w-4 h-4" />
          <span>Disaster Recovery Runbooks (RPO / RTO)</span>
        </button>
      </div>

      {/* SUBTAB 1: BACKUPS */}
      {activeSubTab === 'BACKUPS' && (
        <div className="space-y-4">
          <div className="bg-slate-900 border border-slate-800 p-4 rounded-2xl flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
            <div>
              <h3 className="font-bold text-white text-sm">Automated & Manual Backup Registry</h3>
              <p className="text-slate-400 text-xs">
                Encrypted snapshots stored across dual-region GCP cloud storage with SHA-256 parity.
              </p>
            </div>

            <button
              type="button"
              onClick={handleManualBackup}
              disabled={isCreatingBackup}
              className="bg-amber-600 hover:bg-amber-500 text-slate-950 font-black px-4 py-2.5 rounded-xl flex items-center gap-2 shadow-md transition disabled:opacity-50"
            >
              <Database className={`w-4 h-4 ${isCreatingBackup ? 'animate-pulse' : ''}`} />
              <span>{isCreatingBackup ? 'Generating Snapshot...' : 'Trigger Manual Backup'}</span>
            </button>
          </div>

          {backupSuccessMessage && (
            <div className="bg-emerald-950/80 border border-emerald-500 text-emerald-300 p-3.5 rounded-xl flex items-center gap-2 font-semibold">
              <CheckCircle2 className="w-4 h-4 text-emerald-400 flex-shrink-0" />
              <span>{backupSuccessMessage}</span>
            </div>
          )}

          <div className="bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden shadow-sm">
            <div className="overflow-x-auto">
              <table className="w-full text-left">
                <thead className="bg-slate-850 text-slate-400 border-b border-slate-800 text-[11px] uppercase font-bold">
                  <tr>
                    <th className="p-3.5">Snapshot ID</th>
                    <th className="p-3.5">Type & Source</th>
                    <th className="p-3.5">Size & Integrity</th>
                    <th className="p-3.5">Entity Counts</th>
                    <th className="p-3.5">Storage Location</th>
                    <th className="p-3.5 text-right">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-800">
                  {backupRecords.map((bkp) => (
                    <tr key={bkp.id} className="hover:bg-slate-800/50 transition">
                      <td className="p-3.5">
                        <div className="font-bold text-white font-mono">{bkp.id}</div>
                        <div className="text-[10px] text-slate-400">
                          {new Date(bkp.timestamp).toLocaleString()}
                        </div>
                      </td>
                      <td className="p-3.5">
                        <span className="bg-slate-800 border border-slate-700 px-2 py-0.5 rounded font-mono font-bold text-amber-300">
                          {bkp.type}
                        </span>
                        <div className="text-[10px] text-slate-400 mt-0.5">{bkp.createdBy}</div>
                      </td>
                      <td className="p-3.5">
                        <div className="font-mono text-white">{(bkp.sizeKb / 1024).toFixed(2)} MB</div>
                        <span className="inline-flex items-center gap-1 text-[10px] text-emerald-400 font-bold">
                          <Check className="w-3 h-3" /> SHA-256 Verified
                        </span>
                      </td>
                      <td className="p-3.5 font-mono text-[11px] text-slate-300">
                        {bkp.itemCounts.emergencies} Emg • {bkp.itemCounts.cases} Cases • {bkp.itemCounts.pois} POIs
                      </td>
                      <td className="p-3.5 text-slate-400 font-mono text-[10px] truncate max-w-[200px]">
                        {bkp.storageBucket}
                      </td>
                      <td className="p-3.5 text-right">
                        <button
                          type="button"
                          onClick={() => handleStartRestoreWizard(bkp)}
                          className="bg-amber-600/20 hover:bg-amber-600/30 text-amber-300 border border-amber-500/30 px-3 py-1.5 rounded-lg font-bold transition flex items-center gap-1.5 ml-auto"
                        >
                          <RotateCcw className="w-3.5 h-3.5" />
                          <span>Restore</span>
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      )}

      {/* SUBTAB 2: 8-STEP RESTORE WIZARD */}
      {activeSubTab === 'RESTORE' && (
        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 space-y-5">
          <div className="border-b border-slate-800 pb-3">
            <h3 className="font-bold text-white text-sm flex items-center gap-2">
              <RotateCcw className="w-4 h-4 text-amber-400" />
              <span>Interactive 8-Step Disaster Recovery & Restore Protocol</span>
            </h3>
            <p className="text-slate-400 text-xs">
              Strictly protected database restoration workflow with dry-run validation & management confirmation gate.
            </p>
          </div>

          {/* Step Indicator */}
          <div className="grid grid-cols-4 sm:grid-cols-8 gap-1 text-center font-mono">
            {[1, 2, 3, 4, 5, 6, 7, 8].map((s) => (
              <div
                key={s}
                className={`p-2 rounded-lg border text-[10px] font-bold ${
                  restoreStep === s
                    ? 'bg-amber-600 text-slate-950 border-amber-500 shadow-md'
                    : restoreStep > s
                    ? 'bg-emerald-950 text-emerald-300 border-emerald-800'
                    : 'bg-slate-850 text-slate-500 border-slate-800'
                }`}
              >
                Step {s}
              </div>
            ))}
          </div>

          {/* STEP 1: SELECT BACKUP */}
          {restoreStep === 1 && (
            <div className="space-y-3">
              <h4 className="font-bold text-white text-sm">Step 1: Select Target Backup Snapshot</h4>
              <p className="text-slate-400">Choose the verified snapshot you wish to restore:</p>
              <div className="space-y-2">
                {backupRecords.map((bkp) => (
                  <div
                    key={bkp.id}
                    onClick={() => setSelectedBackupForRestore(bkp)}
                    className={`p-3 rounded-xl border cursor-pointer flex items-center justify-between transition ${
                      selectedBackupForRestore?.id === bkp.id
                        ? 'bg-amber-950/40 border-amber-500 text-white'
                        : 'bg-slate-850 border-slate-800 text-slate-300 hover:bg-slate-800'
                    }`}
                  >
                    <div>
                      <div className="font-bold font-mono">{bkp.id}</div>
                      <div className="text-[11px] text-slate-400">
                        {new Date(bkp.timestamp).toLocaleString()} • {(bkp.sizeKb / 1024).toFixed(2)} MB
                      </div>
                    </div>
                    <span className="font-bold text-amber-400">{bkp.type}</span>
                  </div>
                ))}
              </div>
              <div className="flex justify-end pt-3">
                <button
                  type="button"
                  disabled={!selectedBackupForRestore}
                  onClick={() => setRestoreStep(2)}
                  className="bg-amber-600 hover:bg-amber-500 text-slate-950 font-bold px-4 py-2 rounded-xl disabled:opacity-50"
                >
                  Continue to Step 2: Integrity Verification
                </button>
              </div>
            </div>
          )}

          {/* STEP 2: INTEGRITY VERIFICATION */}
          {restoreStep === 2 && (
            <div className="space-y-3">
              <h4 className="font-bold text-white text-sm">Step 2: SHA-256 Checksum & Parity Verification</h4>
              <div className="bg-slate-950 p-4 rounded-xl font-mono text-[11px] space-y-2 text-slate-300 border border-slate-800">
                <p className="text-emerald-400 font-bold">✓ Source Snapshot: {selectedBackupForRestore?.storageBucket}</p>
                <p>✓ Checksum Hash: {selectedBackupForRestore?.checksum}</p>
                <p className="text-emerald-400">✓ Cryptographic signature match confirmed.</p>
              </div>
              <div className="flex justify-between pt-3">
                <button onClick={() => setRestoreStep(1)} className="text-slate-400">Back</button>
                <button onClick={() => setRestoreStep(3)} className="bg-amber-600 text-slate-950 font-bold px-4 py-2 rounded-xl">
                  Proceed to Step 3: Maintenance Lock
                </button>
              </div>
            </div>
          )}

          {/* STEP 3: MAINTENANCE LOCK */}
          {restoreStep === 3 && (
            <div className="space-y-3">
              <h4 className="font-bold text-white text-sm">Step 3: Lock Write Traffic & Client Isolation</h4>
              <div className="bg-amber-950/40 border border-amber-500/50 p-4 rounded-xl text-amber-200">
                <p className="font-bold">⚠️ Notice:</p>
                <p className="text-xs mt-1">
                  Enabling Maintenance Lock isolates incoming writes while allowing Control Room emergency voice operations to proceed safely offline.
                </p>
              </div>
              <div className="flex justify-between pt-3">
                <button onClick={() => setRestoreStep(2)} className="text-slate-400">Back</button>
                <button onClick={() => setRestoreStep(4)} className="bg-amber-600 text-slate-950 font-bold px-4 py-2 rounded-xl">
                  Acknowledge & Proceed to Step 4: Dry-Run Preview
                </button>
              </div>
            </div>
          )}

          {/* STEP 4: DRY-RUN PREVIEW */}
          {restoreStep === 4 && (
            <div className="space-y-3">
              <h4 className="font-bold text-white text-sm">Step 4: Non-Destructive Dry-Run & Item Count Validation</h4>
              <div className="bg-slate-850 p-4 rounded-xl space-y-2 border border-slate-800">
                <div className="flex justify-between">
                  <span>Emergencies to be restored:</span>
                  <span className="font-bold font-mono text-emerald-400">{selectedBackupForRestore?.itemCounts.emergencies}</span>
                </div>
                <div className="flex justify-between">
                  <span>SAPS Cases to be restored:</span>
                  <span className="font-bold font-mono text-emerald-400">{selectedBackupForRestore?.itemCounts.cases}</span>
                </div>
                <div className="flex justify-between">
                  <span>Persons of Interest (POIs):</span>
                  <span className="font-bold font-mono text-emerald-400">{selectedBackupForRestore?.itemCounts.pois}</span>
                </div>
                <div className="flex justify-between">
                  <span>Vehicles of Interest (VOIs):</span>
                  <span className="font-bold font-mono text-emerald-400">{selectedBackupForRestore?.itemCounts.vois}</span>
                </div>
                <div className="flex justify-between">
                  <span>Immutable Audit Logs:</span>
                  <span className="font-bold font-mono text-emerald-400">{selectedBackupForRestore?.itemCounts.auditLogs}</span>
                </div>
              </div>

              <div className="flex justify-between pt-3">
                <button onClick={() => setRestoreStep(3)} className="text-slate-400">Back</button>
                <button
                  onClick={() => {
                    setIsDryRunVerified(true);
                    setRestoreStep(5);
                  }}
                  className="bg-amber-600 text-slate-950 font-bold px-4 py-2 rounded-xl"
                >
                  Verify Parity & Proceed to Step 5
                </button>
              </div>
            </div>
          )}

          {/* STEP 5: PRE-RESTORE SAFETY SNAPSHOT */}
          {restoreStep === 5 && (
            <div className="space-y-3">
              <h4 className="font-bold text-white text-sm">Step 5: Automated Pre-Restore Safety Snapshot</h4>
              <p className="text-slate-400">
                The system automatically creates an instantaneous checkpoint of current live data before applying the historical snapshot.
              </p>
              <div className="bg-emerald-950/60 border border-emerald-800 p-3 rounded-xl text-emerald-300 font-mono">
                ✓ Safety rollback checkpoint PRE-RESTORE-{Date.now()} created successfully.
              </div>
              <div className="flex justify-between pt-3">
                <button onClick={() => setRestoreStep(4)} className="text-slate-400">Back</button>
                <button onClick={() => setRestoreStep(6)} className="bg-amber-600 text-slate-950 font-bold px-4 py-2 rounded-xl">
                  Proceed to Step 6: Management Gate
                </button>
              </div>
            </div>
          )}

          {/* STEP 6: MANAGEMENT APPROVAL GATE */}
          {restoreStep === 6 && (
            <div className="space-y-3">
              <h4 className="font-bold text-white text-sm">Step 6: Management Authorization Gate</h4>
              <p className="text-slate-400">
                Type <code className="text-amber-400 font-bold">RESTORE-APPROVED</code> below to authorize execution:
              </p>
              <input
                type="text"
                value={managementConfirmText}
                onChange={(e) => setManagementConfirmText(e.target.value)}
                placeholder="Type RESTORE-APPROVED"
                className="w-full bg-slate-850 border border-slate-700 rounded-xl p-3 text-white font-mono"
              />
              <div className="flex justify-between pt-3">
                <button onClick={() => setRestoreStep(5)} className="text-slate-400">Back</button>
                <button
                  disabled={managementConfirmText !== 'RESTORE-APPROVED'}
                  onClick={() => setRestoreStep(7)}
                  className="bg-red-600 hover:bg-red-500 text-white font-bold px-4 py-2 rounded-xl disabled:opacity-40"
                >
                  Authorize Execution & Proceed to Step 7
                </button>
              </div>
            </div>
          )}

          {/* STEP 7: EXECUTE RESTORE */}
          {restoreStep === 7 && (
            <div className="space-y-4 text-center py-6">
              <h4 className="font-bold text-white text-sm">Step 7: Executing Restoration</h4>
              <p className="text-slate-400">Applying data blocks from snapshot {selectedBackupForRestore?.id}...</p>
              <button
                type="button"
                disabled={isRestoring}
                onClick={handleExecuteRestore}
                className="bg-amber-600 hover:bg-amber-500 text-slate-950 font-black px-6 py-3 rounded-xl shadow-lg transition"
              >
                {isRestoring ? 'Applying Changes...' : 'Execute Database Restore Now'}
              </button>
            </div>
          )}

          {/* STEP 8: COMPLETION */}
          {restoreStep === 8 && (
            <div className="space-y-4 text-center py-6">
              <CheckCircle2 className="w-12 h-12 text-emerald-400 mx-auto" />
              <div>
                <h4 className="font-bold text-white text-base">Step 8: Restoration Successfully Completed</h4>
                <p className="text-slate-400 text-xs mt-1">{restoreCompleteMessage}</p>
              </div>
              <button
                type="button"
                onClick={() => {
                  setRestoreStep(1);
                  setActiveSubTab('BACKUPS');
                }}
                className="bg-slate-800 text-white font-bold px-4 py-2 rounded-xl border border-slate-700 hover:bg-slate-700"
              >
                Return to Backup Snapshots
              </button>
            </div>
          )}
        </div>
      )}

      {/* SUBTAB 3: RETENTION POLICIES */}
      {activeSubTab === 'RETENTION' && (
        <div className="bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden shadow-sm">
          <div className="p-4 border-b border-slate-800">
            <h3 className="font-bold text-white text-sm">POPIA & Statutory Data Retention Schedule</h3>
            <p className="text-slate-400 text-xs">
              Configured retention rules balanced between South African privacy law and statutory criminal procedure requirements.
            </p>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-left">
              <thead className="bg-slate-850 text-slate-400 border-b border-slate-800 text-[11px] uppercase font-bold">
                <tr>
                  <th className="p-3.5">Data Category</th>
                  <th className="p-3.5">Retention Period</th>
                  <th className="p-3.5">Days</th>
                  <th className="p-3.5">Legal / Statutory Basis</th>
                  <th className="p-3.5">Auto Purge</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800">
                {RETENTION_POLICIES.map((p, idx) => (
                  <tr key={idx} className="hover:bg-slate-800/50 transition">
                    <td className="p-3.5 font-bold text-white">{p.dataCategory}</td>
                    <td className="p-3.5 text-slate-300">{p.retentionPeriodDescription}</td>
                    <td className="p-3.5 font-mono text-amber-400 font-bold">{p.retentionDays}d</td>
                    <td className="p-3.5 text-slate-400 text-[11px]">{p.statutoryBasis}</td>
                    <td className="p-3.5">
                      <span
                        className={`px-2 py-0.5 rounded font-mono text-[10px] font-bold ${
                          p.autoPurgeEligible
                            ? 'bg-emerald-950 text-emerald-300 border border-emerald-800'
                            : 'bg-slate-800 text-slate-400'
                        }`}
                      >
                        {p.autoPurgeEligible ? 'AUTOMATED' : 'MANUAL APPROVAL'}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* SUBTAB 4: DISASTER RECOVERY RUNBOOKS */}
      {activeSubTab === 'RUNBOOKS' && (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
          <div className="space-y-2">
            <span className="font-bold text-slate-400 uppercase tracking-wider text-[11px] block">
              Incident Scenarios
            </span>
            {DISASTER_RECOVERY_RUNBOOKS.map((rb) => (
              <div
                key={rb.id}
                onClick={() => setSelectedRunbook(rb)}
                className={`p-3 rounded-xl border cursor-pointer transition ${
                  selectedRunbook?.id === rb.id
                    ? 'bg-amber-950/40 border-amber-500 text-white'
                    : 'bg-slate-900 border-slate-800 text-slate-400 hover:text-white'
                }`}
              >
                <div className="flex items-center justify-between">
                  <span className="font-bold text-xs">{rb.incidentType}</span>
                  <span
                    className={`font-mono text-[9px] font-black px-1.5 py-0.5 rounded ${
                      rb.severity === 'CRITICAL'
                        ? 'bg-red-950 text-red-300'
                        : 'bg-amber-950 text-amber-300'
                    }`}
                  >
                    {rb.severity}
                  </span>
                </div>
                <div className="text-[10px] text-slate-500 mt-1">
                  RPO: {rb.rpo} • RTO: {rb.rto}
                </div>
              </div>
            ))}
          </div>

          <div className="lg:col-span-2 bg-slate-900 border border-slate-800 rounded-2xl p-5 space-y-4">
            {selectedRunbook ? (
              <div className="space-y-4">
                <div className="border-b border-slate-800 pb-3 flex justify-between items-start">
                  <div>
                    <h3 className="font-black text-white text-base">{selectedRunbook.incidentType}</h3>
                    <p className="text-slate-400 text-xs mt-0.5">Runbook Protocol ID: {selectedRunbook.id}</p>
                  </div>
                  <div className="text-right font-mono text-[11px]">
                    <div className="text-amber-400 font-bold">RPO Target: {selectedRunbook.rpo}</div>
                    <div className="text-emerald-400 font-bold">RTO Target: {selectedRunbook.rto}</div>
                  </div>
                </div>

                <div className="space-y-2">
                  <h4 className="font-bold text-amber-400 text-xs uppercase tracking-wider">
                    1. Immediate Containment Actions
                  </h4>
                  <ul className="list-disc list-inside space-y-1 text-slate-300">
                    {selectedRunbook.immediateContainment.map((c, i) => (
                      <li key={i}>{c}</li>
                    ))}
                  </ul>
                </div>

                <div className="space-y-2">
                  <h4 className="font-bold text-emerald-400 text-xs uppercase tracking-wider">
                    2. Step-by-Step Restoration Procedure
                  </h4>
                  <ul className="list-disc list-inside space-y-1 text-slate-300">
                    {selectedRunbook.recoverySteps.map((s, i) => (
                      <li key={i}>{s}</li>
                    ))}
                  </ul>
                </div>

                <div className="space-y-2">
                  <h4 className="font-bold text-blue-400 text-xs uppercase tracking-wider">
                    3. Post-Incident Verification
                  </h4>
                  <ul className="list-disc list-inside space-y-1 text-slate-300">
                    {selectedRunbook.postIncidentVerification.map((v, i) => (
                      <li key={i}>{v}</li>
                    ))}
                  </ul>
                </div>
              </div>
            ) : (
              <p className="text-slate-500 text-center py-10">Select an incident scenario from the left.</p>
            )}
          </div>
        </div>
      )}
    </div>
  );
};
